% --- INICIO DE PLANTILLA PERSONALIZADA ---
\documentclass[oneside,11pt]{Latex/Classes/PhDthesisPSnPDF}

% --- Paquetes Originales ---
\usepackage{blindtext}
\usepackage{actuarialangle} 
\usepackage{tabularx}
\usepackage{float}
\usepackage{multirow, array}
\usepackage[usenames,dvipsnames,svgnames,table]{xcolor}
\usepackage{longtable}
\usepackage{latexsym,amsmath,amssymb,amsfonts}
\usepackage{enumitem}
\usepackage{xparse}
\usepackage{booktabs}
\usepackage[round, sort, numbers]{natbib}  
\usepackage{adjustbox}
\usepackage[utf8]{inputenc}
\usepackage{caption}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{cleveref}

% Definición de colores
\definecolor{miblue}{RGB}{68, 114, 196}

% --- CAMBIO CRÍTICO 1: Usar \input para macros en el preámbulo ---
% \include da problemas antes del begin document. \input es seguro.
\input{Latex/Macros/MacroFile1}

% --- Definiciones de seguridad (por si la clase falla al cargar alguna variable) ---
\providecommand{\facultad}[1]{\def\lafacultad{#1}}
\providecommand{\escudofacultad}[1]{\def\elescudo{#1}}
\providecommand{\degree}[1]{\def\elgrado{#1}}
\providecommand{\director}[1]{\def\eldirector{#1}}
\providecommand{\lugar}[1]{\def\ellugar{#1}}
\providecommand{\degreedate}[1]{\def\lafecha{#1}}

% --- Configuración para bloques de código de R (Pandoc) ---
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                         DATOS (Conectados a RMarkdown)                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\title{Título del Trabajo Final}
\author{Rehide De Pablos \\ Moisés Perez \\ Diego Rosabrussin}

% Lógica para Facultad: Si la defines en el YAML la usa, si no, usa la default

\facultad{Facultad de Ciencias Económicas y Sociales \\ Escuela de
Estadistica y Ciencias Actuariales}
  \escudofacultad{Latex/Classes/Escudos/faces}

\degree{Computación I}
\director{Jesus Ochoa \\ Oliver Triveño}
\degreedate{Febrero 2026} 
\lugar{Caracas}

\portadatrue 

% Metadatos PDF
\keywords{}
\subject{}

% --- CORRECCIÓN PARA PANDOC NUEVO (Imágenes) ---
\makeatletter
\providecommand{\pandocbounded}[1]{#1}
\makeatother


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   DOCUMENTO                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{document}

\maketitle

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                  PRÓLOGO                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\frontmatter

% Puedes agregar dedicatorias desde el YAML si quieres, o dejarlas fijas aquí

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   ÍNDICES                         %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\setcounter{secnumdepth}{3}
\setcounter{tocdepth}{3}

\tableofcontents



\cleardoublepage

  \cleardoublepage       % Empieza en página derecha (estándar en tesis)
  \chapter*{Resumen}     % Crea el título "Resumen" sin numeración (Capítulo *)
  \addcontentsline{toc}{chapter}{Resumen} % (Opcional) Lo añade al índice
  
  Resumen del trabajo de
investigación\ldots{}             % Aquí se pega el texto que escribiste en el YAML
  
  \cleardoublepage

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   CONTENIDO (El Corazón)          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\mainmatter
\def\baselinestretch{1.5}

% --- CAMBIO CRÍTICO 2: Aquí RMarkdown inyecta todo tu texto ---
\chapter*{Introducción}

La Fórmula 1 es la máxima categoría del automovilismo mundial, donde la
diferencia entre la victoria y la derrota suele medirse en milésimas de
segundo. Si bien el rendimiento del vehículo y la habilidad del piloto
son fundamentales, el trabajo en equipo durante las paradas en boxes
(\emph{pit stops}) representa un factor crítico en la estrategia de
carrera.

Entre los años 1994 y 2010, la Fórmula 1 atravesó una de sus épocas más
dinámicas, caracterizada por la reintroducción y posterior prohibición
del repostaje de combustible durante las carreras.

Este trabajo de investigación tiene como propósito realizar un análisis
estadístico exhaustivo sobre el conjunto de datos de paradas en boxes de
la F1 en dicho periodo.

A través del uso de herramientas computacionales en R, se busca
descomponer la varianza de los tiempos de parada en función de factores
como la escudería, el año y las estrategias de carrera.

\section{Estructura del informe}

Para cumplir con este propósito, el presente documento técnico se
encuentra estructurado en cinco capítulos fundamentales:

\textbf {Capítulo I} plantea la problemática de la eficiencia operativa,
formulando las preguntas de investigación, los objetivos y delimitando
el estudio.

\textbf {Capítulo II} establece el Marco Teórico, definiendo los
conceptos estadísticos clave necesarios para la interpretación de los
datos.

\textbf {Capítulo III} describe el Marco Metódico, detallando el proceso
de extracción, transformación y limpieza de datos (ETL).

\textbf {Capítulo IV} presenta el Análisis de Resultados, donde se
exhiben las tablas y gráficos generados dinámicamente; y finalmente.

\textbf {Capítulo V} se exponen las Conclusiones y Recomendaciones del
estudio.

\chapter{Planteamiento del Problema}

En la Fórmula 1, el tiempo de permanencia en el pit lane es una variable
de alto impacto que condiciona el resultado deportivo. Durante el ciclo
1994-2010, las reglas respecto a las operaciones permitidas en los boxes
cambiaron drásticamente, siendo el más crítico la reintroducción y
posterior prohibición del repostaje de combustible. El problema central
de esta investigación consiste en evaluar, desde una perspectiva
estadística, la eficiencia operativa de las distintas escuderías durante
el periodo de adaptación a estas normativas de repostaje (1994-1996). La
ausencia de un modelo claro que cuantifique cómo estas variables
categóricas impactan en el tiempo esperado de parada genera la necesidad
de responder a las siguientes preguntas de investigación:

\textbf{1.} ¿Existen diferencias significativas en los tiempos de parada
al comparar el primer \emph{pit stop} de un vehículo con su segunda
parada en boxes?

\textbf{2.} ¿Qué escudería demostró ser la más eficiente y registró los
tiempos promedio de parada más rápidos durante este periodo?

\textbf{3.} ¿Cuáles son las estrategias de paradas (1, 2 o 3 paradas)
más predominantes a lo largo del periodo evaluado?

\section{Justificación}

El análisis temporal de las paradas en boxes trasciende el ámbito
puramente deportivo; representa un caso de estudio ideal sobre cómo los
equipos de alto rendimiento optimizan procesos bajo condiciones de
extrema presión y variabilidad. Se justifica esta investigación en la
oportunidad de aplicar modelos estadísticos para cuantificar el impacto
real que tienen los cambios de normativas externas (como la prohibición
del repostaje) sobre los tiempos de ejecución mecánica. Desde la
perspectiva académica, este trabajo permite demostrar la utilidad del
lenguaje R para depurar, transformar y extraer conclusiones
significativas a partir de registros cronométricos crudos, consolidando
habilidades prácticas en el manejo de distribuciones asimétricas y el
análisis de varianza.

\section{Objetivos}

\subsection{Objetivo General}
\begin{itemize}
  \item{Analizar los patrones históricos y los factores determinantes en los tiempos de las paradas en boxes de la Fórmula 1 (1994-2010) para caracterizar el comportamiento de la eficiencia mecánica de las escuderías.}
\end{itemize}

\subsection{Objetivos Específicos}
\begin{itemize}
  \item{1. Comparar los tiempos registrados según el orden de la parada (primera parada vs. segunda parada) para analizar las razones estadísticas por las cuales el segundo pit stop tiende a presentar un menor tiempo. }
  \item{2.Describir la influencia de la variable escudería en la distribución de los tiempos de los pit stops. }
  \item{3. Analizar la distribución de frecuencias del número de paradas por piloto para identificar las estrategias de carrera.}
\end{itemize}

\section{Cobertura}

\subsection{Horizontal}

La cobertura horizontal abarca las métricas operativas y características
intrínsecas de cada parada en boxes registrada.

\begin{table}[ht]
\centering
\caption{Variables consideradas} 
\resizebox{17cm}{!} {
\begin{tabular}{ccc}
  \hline
\ \ \ \ \ TIPO&VARIABLE&DESCRIPCIÓN \\ 
\hline
          Categórica & Car & Escudería o equipo de mecánicos (e.g., Ferrari, McLaren).\\ 
          Numérica & Year & Año en que se realizó el campeonato.\\ 
          Numérica & Stops & Número de parada en esa carrera para ese piloto.\\ 
          Numérica & Time & Tiempo exacto que transcurre desde que el vehículo entra al pit lane hasta que sale.\\ 
  \hline
\end{tabular}
}
\end{table}

\subsection{Vertical}

La cobertura vertical comprende un total de 9.921 observaciones. Cada
fila representa una parada en boxes única ejecutada durante un Gran
Premio de Fórmula 1. El alcance temporal abarca desde el año 1994 hasta
el año 2010.

\section{Periodo de Referencia}

La fuente de los datos corresponde a un registro histórico estructurado.
El periodo de referencia efectivo para el análisis descriptivo se centra
en el intervalo 1994-2010.

\section{Variables}

La variable principal en estudio es el Tiempo de Parada (Time), la cual
representa la eficiencia operativa del equipo de mecánicos, medida en
los segundos transcurridos durante cada pit stop.

\chapter{Marco Teórico}
\subsection{Bases Teóricas}

El presente análisis se fundamenta en las técnicas de la Estadística
Descriptiva, la cual permite recolectar, organizar, resumir y presentar
los datos de manera informativa. Los principales estadísticos y gráficos
empleados son:

\subsection{Medidas de Tendencia Central)}

Se utilizará la Media Aritmética (promedio de los tiempos de parada) y
la Mediana (el valor central que divide la distribución en dos partes
iguales, siendo robusta ante valores atípicos o outliers).

\[ \bar{x} = \frac{1}{n} \sum_{i=1}^{n} x_i \] \[ Me = \begin{cases} 
x_{\frac{n+1}{2}} & \text{si } n \text{ es impar} \\ 
\frac{x_{\frac{n}{2}} + x_{\frac{n}{2} + 1}}{2} & \text{si } n \text{ es par} 
\end{cases} \]

\subsection{Medidas de Dispersión}

Se aplicará la Desviación Estándar para cuantificar el grado de
variabilidad o dispersión de los tiempos de parada en los boxes respecto
a la media.

\[ s = \sqrt{\frac{1}{n-1} \sum_{i=1}^{n} (x_i - \bar{x})^2} \]

\subsection{Distribución de Frecuencias}

Tablas que resumen cuántas veces ocurre un evento (frecuencia absoluta)
y su proporción (frecuencia relativa), vitales para analizar el número
de paradas por piloto.

\[ f_r = \frac{f_i}{n} \]

\subsection{Gráficos}

Gráfico de Cajas (Boxplot): Herramienta visual que representa la
distribución de los datos a través de sus cuartiles. Es fundamental en
este estudio para comparar visualmente los tiempos de la primera y
segunda parada, identificando rápidamente la mediana y los valores
atípicos.

Gráfico de Barras: Representación gráfica para variables categóricas o
discretas (como Escuderías o número de paradas) que muestra la
frecuencia o promedios mediante barras rectangulares.

\chapter{Marco Metódico}

En esta sección se detalla el proceso de Extracción, Transformación y
Carga (ETL) aplicado al conjunto de datos crudos de la Fórmula 1. La
preparación adecuada de los datos es un paso ineludible antes de aplicar
los modelos descritos en el marco teórico.

\section{Bases metódicas utilizadas en el trabajo de investigación}

El procesamiento de la base de datos se realizó utilizando el entorno R
y el ecosistema de paquetes \texttt{tidyverse}. A continuación, se
detalla el proceso de Extracción, Transformación y Carga (ETL) aplicado
al conjunto de datos crudos de la Fórmula 1.\\

\subsection{1. Carga de Datos}

El primer paso consistió en la importación del archivo plano que
contiene los registros históricos de las paradas en boxes a lo largo de
los diferentes Grandes Premios.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Importación del dataset original}

\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"Dataset/formula 1.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{Extracción, Limpieza y Filtrado de Datos}

El dataset original se importa al entorno de R utilizando la función
read\_csv. Posteriormente, se aplica un proceso de limpieza eliminando
los registros con valores nulos en la variable Time mediante drop\_na().
Finalmente, y de acuerdo a los objetivos de la investigación, se aplica
un filtrado espacial-temporal usando filter(Year \textgreater= 1994 \&
Year \textless= 1996) para acotar el análisis exclusivamente al periodo
de adaptación del repostaje.

Transformación de Tipos de Datos y Filtrado

Para garantizar que el software interprete correctamente la naturaleza
de las variables, se utiliza la función mutate() y as.factor() para
coercionar el Año, la Escudería y el Número de Parada, pasando de ser
tratados como valores numéricos a categorías estadísticas (factores).

Análisis Descriptivo: Consiste en la aplicación de funciones
estadísticas básicas sobre el conjunto de datos limpio para dar
respuesta a las preguntas de investigación, generando resúmenes
numéricos.

\subsubsection{Cálculo de Medidas de Tendencia Central y Dispersión}

Para responder al primer objetivo y obtener la media, la mediana y la
desviación estándar global del periodo 1994-1996, se emplea la función
summarise() de la librería dplyr. Este procedimiento colapsa los miles
de registros en un único cuadro resumen:

\begin{verbatim}
## # A tibble: 1 x 3
##   Media_Segundos Mediana_Segundos Desviacion_Estandar
##            <dbl>            <dbl>               <dbl>
## 1           32.3             30.6                7.08
\end{verbatim}

\subsection{Cálculo de Distribución de Frecuencias}

Para dar respuesta a las estrategias de carrera y conocer cuántas
paradas predominan por piloto, se utiliza la función count() combinada
con mutate() para generar las frecuencias absolutas y relativas.

\begin{verbatim}
## # A tibble: 5 x 3
##   Stops     n Porcentaje
##   <fct> <int>      <dbl>
## 1 1       808     54.3  
## 2 2       516     34.7  
## 3 3       149     10.0  
## 4 4        11      0.739
## 5 5         4      0.269
\end{verbatim}

\subsection{Generación de Gráficos Comparativos (Boxplot)}

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-4-1} \end{center}

\chapter{Análisis de Resultados}

\small Este capítulo presenta los resultados obtenidos al aplicar las
metodologías descritas en el capítulo anterior, así como del análisis
estadístico descriptivo de las variables estudiadas y las ventajas y
desventajas al aplicar dichos tests.

\section{Análisis de Tiempos Generales y Orden de Parada}

De acuerdo con los estadísticos calculados, el tiempo promedio que un
vehículo permaneció en los boxes durante el periodo 1994-1996 fue de
32.3 segundos, con una mediana de 30.6 segundos. La ligera asimetría
hacia la derecha (media mayor que la mediana) y la desviación estándar
de 7.08 segundos indican la presencia de paradas atípicamente largas,
atribuibles a reparaciones imprevistas más allá del simple repostaje de
combustible.

\section{Análisis de Estrategias de Carrera (Frecuencias)}

En respuesta al objetivo de identificar las estrategias predominantes,
la distribución de frecuencias arrojó que la mayoría de los pilotos
optaban por una estrategia conservadora. El 54.3\% de los registros
corresponden a una primera parada, mientras que las segundas paradas
representan el 34.7\%. Las estrategias de tres paradas fueron
considerablemente menos frecuentes (10.0\%), y las de cuatro o cinco
paradas resultan estadísticamente marginales (menos del 1\% en
conjunto). Esto demuestra que durante este trienio, la estrategia
estándar de los equipos era ir a una o máximo dos paradas en boxes.

\section{Comparación de Tiempos por Orden de Parada (Boxplot)}

Para dar respuesta al primer objetivo específico, el gráfico de cajas
(Boxplot) evidencia una clara diferencia en la distribución de los
tiempos al comparar la primera y la segunda parada. Visualmente, la
mediana de la ``Parada 2'' se ubica ligeramente por debajo de la
``Parada 1''. Además, la caja de la segunda parada es más estrecha, lo
que denota una menor dispersión de los datos. Esto sugiere que las
segundas paradas tienden a ser más rápidas y predecibles, posiblemente
debido a que la carga de combustible requerida para cerrar la carrera es
menor que la necesaria a mitad de competencia.

\section{Influencia de la Escudería en la Eficiencia Operativa}

Antes de evaluar los tiempos por equipo, es importante hacer una pequeña
aclaratoria sobre los datos. En nuestra base, la variable Car
(Escudería) agrupa a los equipos usando la combinación de la marca del
auto y su motor (por ejemplo, diferenciando a Benetton Ford de Benetton
Renault).

Como equipo de investigación, decidimos mantener esta separación y
analizarlos como casos distintos. La razón es que cambiar de proveedor
de motor obliga a modificar la estructura trasera del carro y la
ubicación del tanque de gasolina. Físicamente, al ser un diseño
diferente, es lógico pensar que esto afecta la comodidad y la rapidez
con la que los mecánicos pueden hacer su trabajo en los pits.

Aclarado este punto, al calcular el tiempo promedio de parada para cada
escudería, obtuvimos el siguiente gráfico con las 10 más rápidas del
trienio:

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-5-1} \end{center}

Como se puede observar claramente en el gráfico, la escudería Sauber
Ford destacó como la más rápida en la calle de boxes durante este
periodo, registrando el tiempo promedio más bajo entre todos los
competidores. Esto demuestra que la eficiencia en los pits no siempre
dependía de ser el equipo con mayor presupuesto (como Ferrari o
Benetton), sino de la coordinación del equipo de mecánicos y de cómo el
diseño de ese chasis Sauber con motor Ford facilitaba un cambio rápido
de neumáticos y recarga de combustible.

\chapter{Conclusiones y Recomendaciones}

\textbf{1.}Al analizar los tiempos generales y el orden de parada, se
concluye que la segunda parada en boxes tiende a ser más rápida y con
menos variaciones que la primera. Esto se explica porque, por lo
general, en la segunda parada se inyecta menos cantidad de combustible
(solo el necesario para terminar la carrera), lo que recorta los
segundos totales de la operación en comparación con la recarga pesada de
la primera parada.

\textbf{Recomendación} Se sugiere a los equipos de mecánicos enfocar sus
prácticas y simulaciones de entrenamiento principalmente en la primera
parada, buscando técnicas para agilizar la inyección inicial de
combustible, ya que es el momento donde se pierde más tiempo
estadísticamente.

\textbf{2.} En cuanto a las estrategias de carrera, se concluye que ir a
una o dos paradas fue la norma casi absoluta durante el trienio
1994-1996, sumando en conjunto casi el 90\% de las decisiones de los
equipos. Las estrategias de tres o más paradas resultaron ser casos
aislados, probablemente forzados por la lluvia, daños en el auto o
banderas rojas.

\textbf{Recomendación} Para futuras investigaciones, se recomienda
cruzar esta variable de ``número de paradas'' con la posición final en
la que llegó el piloto a la meta. De esta forma, se podría comprobar
matemáticamente si la estrategia de hacer una sola parada realmente
garantizaba ganar la carrera.

\textbf{3.} Sobre la influencia de las escuderías, se concluye que el
tipo de auto y el equipo de trabajo tienen un impacto directo en los
tiempos. El análisis demostró que Sauber Ford fue la estructura más
rápida y eficiente en los pits, logrando superar a constructores
histórica y económicamente más grandes.

\textbf{Recomendación} Se recomienda utilizar los tiempos de Sauber Ford
como punto de referencia (``benchmarking'') para evaluar la eficiencia.
Analizar cómo este equipo distribuía a su personal alrededor del carro
podría servir de modelo para mejorar el rendimiento de los mecánicos más
lentos de la parrilla.

\appendix
\renewcommand{\thechapter}{\Alph{chapter}}

\chapter{Histograma de Distribución Global de Tiempos}

Este gráfico complementa directamente el análisis descriptivo presentado
en el Capítulo 5 (Sección 5.1). Al visualizar el histograma de los
tiempos de parada, se evidencia de forma gráfica la asimetría hacia la
derecha (sesgo positivo) que se mencionó en el informe. La línea roja
punteada, que representa la media aritmética (32.3 segundos), se
encuentra ligeramente desplazada a la derecha de la mayor concentración
de datos. Esto confirma visualmente la hipótesis planteada: la gran
mayoría de las paradas ocurren en la marca de los 30 segundos, pero
existen eventos aislados (paradas atípicamente largas por reparaciones o
accidentes) que arrastran el promedio general hacia arriba.

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-6-1} \end{center}

\chapter{Evolución del Tiempo Promedio por Año}

Este gráfico respalda la justificación central de la investigación
(Capítulo 2), la cual se enfoca en el ``periodo de adaptación'' de la
Fórmula 1 tras la reintroducción del repostaje de combustible. Al
observar la línea de tendencia de los promedios a lo largo de 1994, 1995
y 1996, se puede apreciar la ``curva de aprendizaje'' de los equipos de
mecánicos. Esta visualización permite entender si, a nivel general, la
categoría logró optimizar sus procesos y ser más rápida a medida que se
acostumbraban a la normativa, o si los tiempos de operación se
mantuvieron estables a lo largo del trienio estudiado.

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-7-1} \end{center}

\chapter{Registro de las 5 Paradas Más Rápidas (1994-1996)}

Para complementar el análisis de las escuderías, este anexo presenta un
extracto directo de la base de datos con las 5 paradas en boxes
individuales más rápidas registradas durante el periodo de estudio. Esta
tabla demuestra la capacidad de manipular y ordenar el conjunto de datos
(mediante las funciones arrange y head de la librería dplyr) para aislar
eventos de máxima eficiencia operativa, permitiendo identificar no solo
la escudería, sino al piloto y el año exacto en que se logró la proeza
mecánica.

\begin{verbatim}
## # A tibble: 5 x 5
##   DriverName          Car              Year  Stops  Time
##   <chr>               <fct>            <fct> <fct> <dbl>
## 1 Johnny Herbert      Benetton Renault 1995  1      13.0
## 2 Rubens Barrichello  Jordan Hart      1994  3      14.0
## 3 Mika Hakkinen       McLaren Peugeot  1994  3      14.0
## 4 Jean-Denis Deletraz Larrousse Ford   1994  2      15.7
## 5 Michael Schumacher  Benetton Ford    1994  3      15.9
\end{verbatim}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   REFERENCIAS                     %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Mantenemos la estructura natbib de tu plantilla
\renewcommand{\bibname}{Lista de Referencias}
\bibliographystyle{apalike} 
\bibliography{bibliografia.bib} 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   APÉNDICES                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\end{document}
